# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 967807e1ade63f32d7865a7c9fd796e784f0fc6283dc82619f19f157a3c80efb311673e44fd7682c5ac13887e87da7280d6b8f6ae11385aca169f7114edbbdf7

test:
  secret_key_base: b195875a002d003d60d4dc7131d967ba77d7851f79c0082986c3b6e249a325355e0237374e1874a8a1e44275e19c4da416e18c66e93be67864c5f82b04fb2056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
